CREATE TABLE IF NOT EXISTS ENDERECO(ID int AUTO_INCREMENT primary key,NUMERO varchar(255),RUA varchar (255),CIDADE varchar (255),ESTADO varchar (255));
CREATE TABLE IF NOT EXISTS PACIENTE(ID int AUTO_INCREMENT primary key,NOME varchar(255),SOBRENOME varchar (255),RG varchar (255),DATA_CADASTRO TIMESTAMP WITHOUT TIME ZONE,ENDERECO_ID int);
CREATE TABLE IF NOT EXISTS DENTISTA(ID int AUTO_INCREMENT primary key,NOME varchar(255),SOBRENOME varchar (255),MATRICULA int);
